services:
  fastapi:
    container_name: "fastapi_container"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt

    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
