services:
  db:
    container_name: pgdb
    image: postgres:15
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db123
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    container_name: fastapi_container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt

volumes:
  postgres_data:
